### ISSUE TITLE
X-axis label

### ISSUE THREAD

**Issue by ColesNicholas** [Lakens/shiny_apps#1]
I'm not sure why this app is testing the observe whether the observed difference in group A (circle) significantly differs from the observed difference in group B (square). Would it not be easier to just make the x-axis some raw measurement  (e.g., scores)?

**Comment by Lakens** [comment]
this made total sense! I have re-organized the app. It now calculates one mean, and plots it directly. This makes more sense (it difference from my original idea, but this is better!).
