### ISSUE TITLE
Alternating circles and squares

### ISSUE THREAD

**Issue by ColesNicholas** [Lakens/shiny_apps#2]
Right now the plot does not alternate between showing circles and squares. My guess is that this is happening because it is creating a brand new sample for every observeEvent(input$sampleButton)?

A possible solution (that would have to be implemented across the entire code) is to replace the 'group <- sample(c(1,2),1,1)' solution with logic that states: if input$sampleButton is even, group is 1; else group is 2.  
Note, this might require that input$sampleButton be nested in a as.numeric() function.

**Comment by Lakens** [comment]
great suggestion! Implemented through:
    if((input$sampleButton %% 2) == 0) {
      group <- 1
    } else {
      group <- 2
    }
